<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"> <!-- xmlns tag is to add xacro -->

    <xacro:property name="arm_base_lenght" value="0.1" />
    <xacro:property name="arm_base_width" value="0.1" />
    <xacro:property name="arm_base_height" value="0.02" />
    <xacro:property name="arm_forearm_radius" value="0.02" />
    <xacro:property name="arm_forearm_lenght" value="0.3" />
    <xacro:property name="arm_hand_radius" value="0.02" />
    <xacro:property name="arm_hand_lenght" value="0.3" />
    

    <!-- LINKS -->

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_lenght} ${arm_base_width} ${arm_base_height}"/>
            </geometry>
            <origin xyz="0 0 ${arm_base_height/2.0}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <box size="${arm_base_lenght} ${arm_base_width} ${arm_base_height}"/>
            </geometry>
            <origin xyz="0 0 ${arm_base_height/2.0}" rpy="0 0 0" />    
        </collision>
        <xacro:box_inertia m="0.5" l="${2*arm_base_lenght}" w="${2*arm_base_width}" h="${2*arm_base_height}"
                            xyz="0 0 ${arm_base_height/2.0}" rpy="0 0 0" />
    </link>

    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder radius="${arm_forearm_radius}" length="${arm_forearm_lenght}"/>
            </geometry>
            <origin xyz="0 0 ${arm_forearm_lenght/2.0}" rpy="0 0 0" />
            <material name="yellow" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${arm_forearm_radius}" length="${arm_forearm_lenght}"/>
            </geometry>
            <origin xyz="0 0 ${arm_forearm_lenght/2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.3" h="${2*arm_forearm_lenght}" r="${2*arm_forearm_radius}"
                                xyz="0 0 ${arm_forearm_lenght/2.0}" rpy="0 0 0" />
    </link>

    <link name="hand_link">
        <visual>
            <geometry>
                <cylinder radius="${arm_hand_radius}" length="${arm_hand_lenght}"/>
            </geometry>
            <origin xyz="0 0 ${arm_hand_lenght/2.0}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${arm_hand_radius}" length="${arm_hand_lenght}"/>
            </geometry>
            <origin xyz="0 0 ${arm_hand_lenght/2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.3" h="${2*arm_hand_lenght}" r="${2*arm_hand_radius}"
                                xyz="0 0 ${arm_hand_lenght/2.0}" rpy="0 0 0" />
    </link>
    
    <!-- JOINTS -->
    
    <joint name="base_arm_forearm_joint" type="revolute">
       <parent link="arm_base_link"/>
       <child link="forearm_link"/>
       <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0" />
       <axis xyz="0 1 0" />
       <limit lower="0" upper="${pi / 2.0}" effort="100.0" velocity="100" />
       <dynamics friction="0.05" damping="0.1" />
    </joint>

    <joint name="forearm_hand_joint" type="revolute">
        <parent link="forearm_link"/>
        <child link="hand_link"/>
        <origin xyz="0 0 ${arm_forearm_lenght}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="0" upper="${pi / 2.0}" effort="100" velocity="100" />
        <dynamics friction="0.05" damping="0.1" />
    </joint>

</robot>