<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.6" /> <!-- This is to create a variable -->
    <xacro:property name="base_width" value="0.4" /> <!-- This is to create a variable -->
    <xacro:property name="base_height" value="0.2" /> <!-- This is to create a variable -->
    <xacro:property name="wheel_radius" value="0.1" /> <!-- This is to create a variable -->
    <xacro:property name="wheel_length" value="0.05" /> <!-- This is to create a variable -->

    <!--<xacro:macro name="example_macro" params="a b c">
        <link name="dummy_link">
            <geometry>
                <box size="${a} ${b} ${c}" />
            </geometry>
        </link>
    </xacro:macro>

    <xacro:example_macro a="2" b="3" c="4" /> -->

    

    <!-- LINKS -->

    <link name="base_footprint">

    </link>



    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />  <!--size is large, wide and height -->
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="green"/>    <!-- Add material to joint -->
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />  <!--size is large, wide and height -->
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}" xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
                <material name="grey"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
            </collision>
            <xacro:cylinder_inertia m="1.0" h="${2*wheel_length}" r="${2*wheel_radius}"
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" /> 
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />

    <!--<link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
            <material name="grey"/>
        </visual>
    </link>

    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
            <material name="grey"/>
        </visual>
    </link>-->

    <link name="caster_wheel_link">
        <visual>
             <geometry>
                <sphere radius="${wheel_radius / 2.0}"/>
             </geometry>
             <origin xyz="0 0 0" rpy="0 0 0"/>
             <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:sphere_inertia m="0.5" r="${2*wheel_radius / 2.0}" xyz="0 0 0" rpy="0 0 0" />         
    </link>

    <!-- JOINTS -->
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>


    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="${-base_length / 4.0} ${-((base_width/2.0) + (wheel_length/2.0))} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="${-base_length / 4.0} ${(base_width/2.0) + (wheel_length/2.0)} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_link"/>
        <origin xyz="${base_length / 3.0} 0 ${-wheel_radius / 2.0}" rpy="0 0 0"/>
    </joint>

</robot>